name: Docker Image CI

on:
  push:
    branches: [ "main", "develop" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Generate weatherbit client
        run: ./gradlew openApiGenerate
      - name: Build with Gradle Wrapper
        run: ./gradlew clean bootJar -x test
      - name: Set version as env variable
        run: echo "VERSION_INFORMATION=$(./gradlew -q printVersionInformation)" >> $GITHUB_ENV
      - name: Set current date as env variable
        run: echo "NOW=$(date +'%s')" >> $GITHUB_ENV
      - name: Log in to Docker Hub
        id: login
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          # Dockerhub is the default registry
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: ./weather/
          file: ./weather/Dockerfile
          push: true
          tags: |
            pierre1405/personal:${{ env.VERSION_INFORMATION }}-${{ env.NOW }}
            pierre1405/personal:${{ env.VERSION_INFORMATION }}
            pierre1405/personal:latest
          labels: "stacklabs/weather"